### PR TITLE
replace npm with pnpm

### PR DESCRIPTION
**Pull request by perryd01**
- swaps npm lock to pnpm
- updates all packages

### CODE REVIEW

**Comment by FearsomeRover** [comment]
Hmm. At this scale im not sure, if we need to use pnpm. Its probably easier for the others, if we stick to npm for now. But the version updates are welcome for sure.

**Comment by perryd01** [comment]
well, its easy to [install it on any OS](https://pnpm.io/installation#using-a-standalone-script), also used by [Next. js (since it works great with monorepos)](https://github.com/vercel/next.js/blob/canary/pnpm-lock.yaml) and [often outperforms npm](https://github.com/pnpm/pnpm?tab=readme-ov-file#benchmark) on clean installs.

**Comment by perryd01** [comment]
updated packages with npm in #4

**Comment by perryd01** [comment]
wont do

**Pull request closed without merging**
